services:
  # Frontend (Nginx serving static files)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../Front-end/html:/usr/share/nginx/html/html:ro
      - ../Front-end/css:/usr/share/nginx/html/css:ro
      - ../Front-end/js:/usr/share/nginx/html/js:ro
      - ./data/documents:/usr/share/nginx/html/pdf:ro
      - ../Front-end/html/index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped
    container_name: interparents-frontend
    depends_on:
      - backend
    networks:
      - interparents-network

  # Backend API (Node.js/Express with Supabase)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: interparents-backend
    networks:
      - interparents-network

networks:
  interparents-network:
    driver: bridge